Document the std and no_std repositories
esp-rs/book pull request #19
Opened 2022-01-04 11:34 UTC by alvaroarenas

Although the std and no_std are specified in the ecosystem overview,  It is still confusing for newcomers what actual crate should be used. This PR attempts to be more specific with the relationship between the library name (std and no_std) and  the crate name.

2022-01-05 13:38 UTC, MabezDev requested changes
Thanks! Just a little typo to fix and this is good to go :)

2022-01-05 13:38 UTC, MabezDev commented on src/overview.md
> +There are a number of factors which must be considered when choosing between `std` (esp-idf-hal) and `no_std` (esp32-ha). As stated earlier, each approach has its own unique set of advantages and dis
missing an 'l' on the end of esp32-hal

2022-01-06 15:07 UTC, alvaroarenas commented on src/overview.md
> +There are a number of factors which must be considered when choosing between `std` (esp-idf-hal) and `no_std` (esp32-ha). As stated earlier, each approach has its own unique set of advantages and dis
@MabezDev Fixed

2022-01-06 20:07 UTC, jessebraham approved these changes

2022-01-06 20:07 UTC, merged