Installation chapter update
esp-rs/book pull request #70
Opened 2023-02-22 11:00 UTC by SergioGasquez

The installation chapter was a bit outdated since `espup` had a lot of big changes (https://github.com/esp-rs/espup/discussions/154 and https://github.com/esp-rs/espup/pulls?q=is%3Apr+is%3Aclosed) and the container images had some changes too (https://github.com/esp-rs/rust-build/pull/190).

2023-03-03 10:12 UTC, f-hollow commented on src/installation/index.md
> +## Rust installation
Test

2023-03-09 09:11 UTC, f-hollow requested changes
This is part of the comments I have so far.

I need to ask @SergioGasquez some questions before I can finalize my other comments.

2023-03-09 09:56 UTC, SergioGasquez commented on src/installation/index.md
> +  - Users do not need to install ESP-IDf as it is automatically installed by [`esp-idf-sys`] (a crate that all `std` projects need to use).
Do not list it, as the user does to install it. We could mention that it will be handled by esp-idf-sys but, out of the list

2023-03-09 14:40 UTC, SergioGasquez commented on src/installation/index.md
> +curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh
Just removed this link and added a reference to the alternative installation methods.

2023-03-09 14:54 UTC, SergioGasquez commented on src/installation/index.md
> +To develop applications for ESP devices using Rust, you need to install the Rust compiler along with the appropriate toolchain and target(s). Depending on your device, it may be one of two architectu
Target, in our case, is the ESP device, the device you want to build for. Here is the Rust definition: https://doc.rust-lang.org/rustc/targets/index.html

2023-03-09 15:50 UTC, SergioGasquez commented on src/installation/index.md
> +
Thanks for the suggestion, just added the suggested table and a similar table for the difference on the dependencies for std/no_std

2023-03-29 09:01 UTC, closed without merging